export enum FilterBy {
    NUMBER_PERSON = 'NUMBER_PERSON',
    ORDER_CRESCENT = 'ORDER_CRESCENT',
    TOTAL_ENTERPRISES = 'TOTAL_ENTERPRISES',
    TOTAL_MAN_WOMAN = 'TOTAL_MAN_WOMAN',
    AVERAGE_AGE = 'AVERAGE_AGE'
}